In [2]:
import pandas as pd
import numpy as np
print("import done")

import done

In [5]:
df = pd.read_csv("../Dataset/Employees.csv")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [6]:
df.dropna(axis = 1, how='all', inplace=True)

In [7]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [8]:
df = pd.read_csv("../Dataset/Fraud Detection Dataset.csv")
df

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [9]:
df['Time_of_Transaction'].unique()

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [10]:
df['Device_Used'].unique()

<StringArray>
['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device']
Length: 5, dtype: str

In [11]:
df['Device_Used'].mode()

0    Desktop
Name: Device_Used, dtype: str

In [12]:
df['Location'].unique()

<StringArray>
['San Francisco',      'New York',             nan,       'Chicago',
        'Boston',       'Houston',         'Miami',   'Los Angeles',
       'Seattle']
Length: 9, dtype: str

In [13]:
df['Payment_Method'].unique()

<StringArray>
['Debit Card', 'Credit Card', nan, 'UPI', 'Net Banking', 'Invalid Method']
Length: 6, dtype: str

In [15]:
# later in machine learning we will learn how to fill the data using machine learning algorithms, for now, just use unknown if you dont know the data,

In [16]:
# filling data in missing values is called imputation, done by data engineer eh?

In [17]:
df['Time_of_Transaction'] = df['Time_of_Transaction'].fillna(0)

In [18]:
df['Device_Used']= df['Device_Used'].fillna('Unknown Device')

In [19]:
df['Location'] = df['Location'].fillna('Unknown Location')

In [20]:
df['Payment_Method']= df['Payment_Method'].fillna('Unknown Method')

In [21]:
df.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                            0
Location                               0
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                         0
Fraudulent                             0
dtype: int64

In [22]:
df['Time_of_Transaction'] = df['Time_of_Transaction'].astype(int)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  str
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  str
 4   Time_of_Transaction               51000 non-null  int64
 5   Device_Used                       51000 non-null  str
 6   Location                          51000 non-null  str
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    51000 non-null  str
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(1), int64(6), str(5)
memory usage: 4.7 MB

### Remove Unwanted Data

1. " a    bc wijasdnfpasdkfwewf        "   -> white spaces
2. !@#$%^&*(){}:"<>?,./;'[]     -> special characters /regex(regular expression)
3. string functions   -> replace(), strip() => remove white space, LStrip() and RStrip are also there !!! ;)

In [25]:
df = pd.read_csv("../Dataset/HR_Dataset Refresh.csv")
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    str
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    str
 22  DateofTermination           196 non-null    str
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), str(18)
memory usage: 163.8 KB

In [29]:
# have a nice day ;)

In [28]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [30]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

C:\Users\Acer\AppData\Local\Temp\ipykernel_40824\2864691023.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

Index(['Employee_Name', 'Position', 'State', 'DOB', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date'],
      dtype='str')

In [31]:
columns = ['Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore']

for col in columns:
    unique = df[col].unique()
    print(col)
    print('-' * 20)
    print(unique)
    print("\n")

Position
--------------------
<StringArray>
[     'Production Technician I',                      'Sr. DBA',
     'Production Technician II',            'Software Engineer',
                   'IT Support',                 'Data Analyst',
       'Database Administrator',         'Enterprise Architect',
               'Sr. Accountant',           'Production Manager',
                 'Accountant I',           'Area Sales Manager',
 'Software Engineering Manager',                  'BI Director',
       'Director of Operations',         'Sr. Network Engineer',
                'Sales Manager',                 'BI Developer',
         'IT Manager - Support',             'Network Engineer',
                  'IT Director',            'Director of Sales',
     'Administrative Assistant',              'President & CEO',
          'Senior BI Developer',      'Shared Services Manager',
           'IT Manager - Infra',     'Principal Data Architect',
               'Data Architect',              'IT Manager - DB',
                'Data Analyst ',                          'CIO']
Length: 32, dtype: str


State
--------------------
<StringArray>
['MA', 'TX', 'CT', 'VA', 'VT', 'AL', 'WA', 'CA', 'OH', 'IN', 'TN', 'NH', 'RI',
 'PA', 'CO', 'NY', 'UT', 'GA', 'FL', 'NC', 'KY', 'ID', 'NV', 'MT', 'OR', 'ND',
 'AZ', 'ME']
Length: 28, dtype: str


Gender
--------------------
<StringArray>
['M ', 'F']
Length: 2, dtype: str


MaritalDesc
--------------------
<StringArray>
['Single', 'Married', 'Divorced', 'Widowed', 'Separated']
Length: 5, dtype: str


CitizenDesc
--------------------
<StringArray>
['US Citizen', 'Eligible NonCitizen', 'Non-Citizen']
Length: 3, dtype: str


HispanicLatino
--------------------
<StringArray>
['No', 'Yes', 'no', 'yes']
Length: 4, dtype: str


RaceDesc
--------------------
<StringArray>
[                           'White',        'Black or African American',
                'Two or more races',                            'Asian',
 'American Indian or Alaska Native',                         'Hispanic']
Length: 6, dtype: str


TermReason
--------------------
<StringArray>
[               'N/A-StillEmployed',                    'career change',
                            'hours',                 'return to school',
                 'Another position',                          'unhappy',
                       'attendance',                      'performance',
    'Learned that he is a gangster',                         'retiring',
           'relocation out of area',                       'more money',
                         'military',                 'no-call, no-show',
                 'Fatal attraction', 'maternity leave - did not return',
                   'medical issues',                 'gross misconduct']
Length: 18, dtype: str


EmploymentStatus
--------------------
<StringArray>
['Active', 'Voluntarily Terminated', 'Terminated for Cause']
Length: 3, dtype: str


Department
--------------------
<StringArray>
[   'Production       ',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str


ManagerName
--------------------
<StringArray>
[    'Michael Albert',         'Simon Roup',     'Kissy Sullivan',
       'Elijiah Gray',     'Webster Butler',           'Amy Dunn',
    'Alex Sweetwater',      'Ketsia Liebig',     'Brannon Miller',
       'Peter Monroe',      'David Stanley',      'Kelley Spirea',
 'Brandon R. LeBlanc',         'Janet King',         'John Smith',
    'Jennifer Zamora',      'Lynn Daneault',       'Eric Dougall',
     'Debra Houlihan',   'Brian Champaigne', 'Board of Directors']
Length: 21, dtype: str


RecruitmentSource
--------------------
<StringArray>
[               'LinkedIn',                  'Indeed',
           'Google Search',       'Employee Referral',
      'Diversity Job Fair', 'On-line Web application',
           'CareerBuilder',                 'Website',
                   'Other']
Length: 9, dtype: str


PerformanceScore
--------------------
<StringArray>
['Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP']
Length: 4, dtype: str